Updated bucket names from oicr.icgc.test to score.data and score.state
CancerCollaboratory/storage pull request #432
Opened 2024-07-11 20:21 UTC by Azher2Ali

This PR updates the bucket names used in the codebase from **oicr.icgc.test** to **score.data** for **BUCKET_NAME_OBJECT** and from **oicr.icgc.test** to **score.state** for **BUCKET_NAME_STATE**. 

Previously, the buckets **oicr.icgc.test** were referenced in the configuration. This change aligns the code with using score.data and score.state as the new bucket names, reflecting recent updates in the storage infrastructure.

2024-07-19 20:13 UTC, joneubank commented
I attached the relevant ticket and added a detail. The Make file references these bucket names, can we also update that file?

2024-07-22 13:41 UTC, joneubank approved these changes, later dismissed
Thanks!

2024-07-30 18:09 UTC, joneubank submitted a review, later dismissed

2024-08-06 18:55 UTC, leoraba requested changes
Found some references to project specific bucket names like `oicr.icgc`/`oicr.icgc.state` along the code. Found on the application.yml and on some tests.

2024-08-07 14:12 UTC, Azher2Ali commented
> Found some references to project specific bucket names like `oicr.icgc`/`oicr.icgc.state` along the code. Found on the application.yml and on some tests.

Thanks for the feedback @leoraba, the following PR only holds changes related to docker-compose and make file. Rest changes to application and test files are being addressed into seperate PR.

2024-08-09 18:24 UTC, closed without merging