Refactor/unify_manifestv1
CancerCollaboratory/storage pull request #434
Opened 2024-07-15 18:03 UTC by Azher2Ali

This PR refactors the manifest handling implementation in SCORe to consolidate support for a single manifest format, removing the KF-specific implementation in favor of a unified approach. Previously, SCORe provided separate implementations labeled 'icgc' and 'kf' for file download manifests.
 

- [ ] Removed the java/bio/overture/score/client/manifest/kf package entirely.

- [ ] Renamed IcgcManifestService to ManifestServiceImpl.

- [ ]  Eliminated all references of @Profile("!kf") from classes in java/bio/overture/score/client/manifest.

- [ ] Unified manifest download/upload implementations by refactoring Kf and icgc packages under manifest, creating common implementation classes.

2024-07-16 19:28 UTC, joneubank requested changes
All the manifest package changes are good.

Looks like you mixed in one commit here updating the docker buckets. That change needs an additional fix. If you want you can add in the fix to this PR and update the description to inlcude that change, or remove the commit that modified the docker-compose and move those changes to another PR.

2024-07-16 19:28 UTC, joneubank commented on docker-compose.yml
> +      - "./docker/object-storage-init/data/score.data/data:/score-data:ro"
Can you rename the directory this references too? This folder needs to match the volume referenced here.

https://github.com/overture-stack/score/tree/develop/docker/object-storage-init/data/oicr.icgc.test/data

2024-07-18 14:39 UTC, Azher2Ali commented
The updated PR only contains changes related to Unifying the Manifests for KF and ICGC.

2024-07-19 20:05 UTC, joneubank submitted a review, later dismissed

2024-07-23 17:50 UTC, joneubank approved these changes, later dismissed
Repeating approval. Can you update the PR title to describe what is being done here, not autogenerated from the branch name?

2024-07-24 18:51 UTC, Azher2Ali commented
> Repeating approval. Can you update the PR title to describe what is being done here, not autogenerated from the branch name?

Earlier this PR also included changes other than unifying manifest, which later was partioned into a seperate ticket. Now this PR only holds changes to eliminating the KF profiles and refacorting manifests.

2024-07-30 18:10 UTC, joneubank approved these changes, later dismissed
Please update the PR title to describe the changes being made instead of being the text autogenerated from the branch name.

2024-08-01 20:50 UTC, leoraba submitted a review, later dismissed
LGTM

2024-08-07 13:43 UTC, joneubank approved these changes, later dismissed
Reapproving after stale review was dismissed.

2024-08-07 13:44 UTC, joneubank commented
I don't know why the approvals keep getting dismissed here. @Azher2Ali do you need a hand getting this merged?

2024-08-07 14:06 UTC, Azher2Ali commented
I just found out that the issue is with rebasing. Let me just take a final look, if that's not helping will surely reach out.

2024-08-08 09:12 UTC, Azher2Ali commented
Closing this PR, due to rebasing conflicts

2024-08-08 09:12 UTC, closed without merging