Removing ICGC support contact info currently which are inside the SCO…
CancerCollaboratory/storage pull request #453
Opened 2024-07-24 18:29 UTC by Azher2Ali

#443

2024-07-30 18:16 UTC, joneubank requested changes

2024-07-30 18:16 UTC, joneubank commented on score-client/Dockerfile
> +MAINTAINER SCORe <>
Just remove the MAINTAINER statement, this is deprecated in docker: https://docs.docker.com/reference/dockerfile/#maintainer-deprecated

2024-07-30 18:16 UTC, joneubank commented on score-client/src/main/java/bio/overture/score/client/command/VersionCommand.java
> +  private static final String SUPPORT_EMAIL = "";
Remove completely.

2024-08-08 15:51 UTC, leoraba approved these changes
LGTM

2024-08-09 20:51 UTC, joneubank approved these changes

2024-08-09 21:27 UTC, merged